name: rmd-tests

on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master
      - development

jobs:
  unit-tests:
    runs-on: ubuntu-18.04
    container:
      image: docker://hopkinsidd/covidscenariopipeline:latest
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install covidImportation
        run: install.packages(".", type="source", repos=NULL)
        shell: Rscript {0}
      - name: Run tutorial markdown
        env: CENSUS_API_KEY: ${{ secrets.CENSUS_API_KEY }}
        run: rmarkdown::render("covidImportation_tutorial.Rmd")
        shell: Rscript {0}

      # - name: Run integration tests
      #   env: 
      #     CENSUS_API_KEY: ${{ secrets.CENSUS_API_KEY }}
      #   run: |
      #     Rscript local_install.R
      #     cd test
      #     /home/app/python_venv/bin/pytest run_tests.py
      #   shell: bash


